
//ImageTypes
(FixedInternalImagePixelType "float")
(FixedImageDimension 3)
(MovingInternalImagePixelType "float")
(MovingImageDimension 3)
(UseDirectionCosines "true")

//Components
(Registration "MultiMetricMultiResolutionRegistration")
(FixedImagePyramid "FixedSmoothingImagePyramid")
(MovingImagePyramid "MovingSmoothingImagePyramid")
(Interpolator "BSplineInterpolator")
(UseNormalization "true")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")
(Transform "BSplineTransform")

//(ErodeMask "false" )
(ErodeFixedMask "true" )
(ErodeMovingMask "false" )

(NumberOfResolutions 5)
(GridSpacingSchedule 16.0 8.0 4.0 2.0 1.0)

(HowToCombineTransforms "Compose")

(WriteTransformParametersEachIteration "false")
(WriteResultImage "false")
(CompressResultImage "true")
(ResultImageFormat "nii")
(WriteResultImageAfterEachResolution "false") 
(ShowExactMetricValue "false")
(ResultImagePixelType "float")

//Maximum number of iterations in each resolution level:
(MaximumNumberOfIterations 2000 ) 

//Number of grey level bins in each resolution level:
(NumberOfHistogramBins 32 )
(FixedLimitRangeRatio 0.0)
(MovingLimitRangeRatio 0.0)
(FixedKernelBSplineOrder 3)
(MovingKernelBSplineOrder 3)
(UseFastAndLowMemoryVersion "true")

//Number of spatial samples used to compute the mutual information in each resolution level:
(ImageSampler "RandomCoordinate")
(FixedImageBSplineInterpolationOrder 1 )
//(UseRandomSampleRegion "true")
(SampleRegionSize 50.0 50.0 50.0)
(NumberOfSpatialSamples 2000 )
(NewSamplesEveryIteration "true")
(CheckNumberOfSamples "true")
(MaximumNumberOfSamplingAttempts 10)

//Order of B-Spline interpolation used in each resolution level:
(BSplineInterpolationOrder 1)

//Order of B-Spline interpolation used for applying the final deformation:
(FinalBSplineInterpolationOrder 3)

//Default pixel value for pixels that come from outside the picture:
(DefaultPixelValue 0)

//SP: Param_a in each resolution level. a_k = a/(A+k+1)^alpha
(SP_a 10000.0 )

//SP: Param_A in each resolution level. a_k = a/(A+k+1)^alpha
//(SP_A 100.0 ) // is set dependent on randomsampleregion

//SP: Param_alpha in each resolution level. a_k = a/(A+k+1)^alpha
(SP_alpha 0.6 ) 

// Applicable for ASGD, ignored for other metrics
(MaximumStepLength 0.2 ) 
// settings varied in optimization
(FinalGridSpacingInPhysicalUnits 3.0 3.0 3.0)
(Metric "AdvancedNormalizedCorrelation" "TransformBendingEnergyPenalty")
(FixedImagePyramidSchedule 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1)
(MovingImagePyramidSchedule 16 16 16 8 8 8 4 4 4 2 2 2 1 1 1)
(Metric0Weight 1)
(Metric1Weight 1)
(UseRandomSampleRegion "true")
(SP_A 100.0 )
(Optimizer "AdaptiveStochasticGradientDescent")
