FixedInternalImagePixelType = "float"
MovingInternalImagePixelType = "float"
FixedImageDimension = 3
MovingImageDimension = 3
UseDirectionCosines = true
Registration = "MultiResolutionRegistration"
Interpolator = "BSplineInterpolator"
ResampleInterpolator = "FinalBSplineInterpolator"
Resampler = "DefaultResampler"
FixedImagePyramid = "FixedRecursiveImagePyramid"
MovingImagePyramid = "MovingRecursiveImagePyramid"
Optimizer = "AdaptiveStochasticGradientDescent"
Transform = "BSplineTransform"
Metric = "DisplacementMagnitudePenalty"
AutomaticScalesEstimation = true
AutomaticTransformInitialization = true
HowToCombineTransforms = "Compose"
NumberOfHistogramBins = 32
ErodeMask = false
NumberOfResolutions = 2
MaximumNumberOfIterations = 1000
NumberOfSpatialSamples = 2048
NewSamplesEveryIteration = true
ImageSampler = "Random"
BSplineInterpolationOrder = 1
FinalBSplineInterpolationOrder = 1
DefaultPixelValue = 0
WriteResultImage = true
ResultImagePixelType = "float"
ResultImageFormat = "nii"
