// *********************
// * ImageTypes
// *********************
(FixedInternalImagePixelType "short")
(FixedImageDimension 3)
(MovingInternalImagePixelType "short")
(MovingImageDimension 3)

// *********************
// * Components
// *********************
(Registration "MultiResolutionRegistration" )
(FixedImagePyramid "FixedSmoothingImagePyramid")
(MovingImagePyramid "MovingSmoothingImagePyramid")
(Interpolator "BSplineInterpolator")
(BSplineInterpolationOrder 1)
(Metric "AdvancedMeanSquares")
(Optimizer "AdaptiveStochasticGradientDescent")
(ResampleInterpolator "FinalLinearInterpolator")
(Resampler "DefaultResampler")
(Transform "BSplineTransform")

// *********************
// * Optimizer settings
// *********************
(NumberOfResolutions 4)
(FinalGridSpacingInPhysicalUnits 13.0 13.0 13.0 2.0)
(GridSpacingSchedule 8.0 8.0 8.0 4.0 4.0 4.0 2.0 2.0 2.0 1.0 1.0 1.0)
(MaximumNumberOfIterations 2000 2000 2000 2000)
(SP_A 20.0)
(SigmoidInitialTime 1.0)
(AutomaticParameterEstimation "true")

// *********************
// * Mask settings
// *********************
(ErodeMask "false")
(ErodeFixedMask "false")

// *********************
// * Transform settings
// *********************
(HowToCombineTransforms "Compose" )

// *********************
// * Pyramid settings
// *********************
(FixedImagePyramidSchedule 8 8 8 4 4 4 2 2 2 1 1 1)
(MovingImagePyramidSchedule 8 8 8 4 4 4 2 2 2 1 1 1)

// *********************
// * Sampler parameters
// *********************
// The variance metric is allowed to get random samples, the penalty term isn't,
// because of the langrage multipliers, which should correspond to the same
// sample locations in every iteration
(ImageSampler "RandomSparseMask")
(NumberOfSpatialSamples 2000 2000 2000 2000)
(CheckNumberOfSamples "false")
(NewSamplesEveryIteration "true")
(UseRandomSampleRegion "false")
(MaximumNumberOfSamplingAttempts 50)

// *********************
// * Output settings
// *********************
(WriteTransformParametersEachIteration "false" )
(WriteTransformParametersEachResolution "true" )
(WriteResultImage "false" )
(CompressResultImage "false" )
(WriteResultImageAfterEachResolution "false")
(ShowExactMetricValue "false" )
(DefaultPixelValue 0)

