// *********************
// * ImageTypes
// *********************
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(FixedImageDimension 4)
(MovingImageDimension 4)

(UseDirectionCosines "true")

// *********************
// * Components
// *********************
(Registration "MultiResolutionRegistration")
(Interpolator "ReducedDimensionBSplineInterpolator")
(ResampleInterpolator "FinalReducedDimensionBSplineInterpolator")
(Resampler "DefaultResampler")
(BSplineInterpolationOrder 1)
(FinalBSplineInterpolationOrder 3)
(FixedImagePyramid "FixedSmoothingImagePyramid")
(MovingImagePyramid "MovingSmoothingImagePyramid")
(Optimizer "AdaptiveStochasticGradientDescent")
(HowToCombineTransforms "Compose")

//Choose on of the following groupwise transforms:
(Transform "BSplineStackTransform")
//(Transform "AffineLogStackTransform")

//Specific for AffineLogStackTransform
//(AutomaticScalesEstimationStackTransform "true")

//Choose one of the following groupwise metrics:
(Metric "PCAMetric2")
//(Metric "PCAMetric")
//(Metric "LinearGroupwiseMI")
//(Metric "SumOfPairwiseCorrelationCoefficientsMetric")
//(Metric "VarianceOverLastDimensionMetric")

//Specific for the LinearGroupwiseMI metric
(TemplateImage "ArithmeticAverage" "ArithmeticAverage")
(Combination "Sum" "Sum")
(UseFastAndLowMemoryVersion "true")
(NumberOfFixedHistogramBins 32)
(NumberOfMovingHistogramBins 32)

//Specific for the PCAMetric
(NumEigenValues 4)

// *********************
// * Groupwise Metric settings
// *********************
(SubtractMean "true")
(MovingImageDerivativeScales 1 1 1 0)

//Choose one of the following settings:
(FinalGridSpacingInPhysicalUnits 32)
//(FinalGridSpacingInPhysicalUnits 64)
//(FinalGridSpacingInPhysicalUnits 128)

// *********************
// * Optimizer settings
// *********************
(NumberOfResolutions 2)
(AutomaticParameterEstimation "true")
(ASGDParameterEstimationMethod "Original")
(MaximumNumberOfIterations 1000)

// *********************
// * Pyramid settings
// *********************
(ImagePyramidSchedule 2 2 2 0 1 1 1 0)

// *********************
// * Sampler parameters
// *********************
(NumberOfSpatialSamples 2048)
(NewSamplesEveryIteration "true")
(ImageSampler "RandomCoordinate")
(CheckNumberOfSamples "true")

// *********************
// * Mask settings
// *********************
(ErodeMask "false")
(ErodeFixedMask "false")

// *********************
// * Output settings
// *********************
(DefaultPixelValue 0)
(WriteResultImage "true")
(ResultImagePixelType "float")
(ResultImageFormat "nii.gz")
