(AutomaticParameterEstimation "true")
(AutomaticScalesEstimation "true")
(AutomaticTransformInitialization "true")
(AutomaticTransformInitializationMethod "GeometricalCenter")
(BSplineInterpolationOrder 3)
(CheckNumberOfSamples "true")
(DefaultPixelValue 0)
(ErodeMask "true")
(FinalBSplineInterpolationOrder 3)
(FixedImageDimension 3)
(FixedImagePyramid "FixedRecursiveImagePyramid")
(FixedInternalImagePixelType "float")
(HowToCombineTransforms "Compose")
(ImagePyramidSchedule 8 8 4 4 4 2 2 2 1)
(ImageSampler "Random")
(Interpolator "BSplineInterpolator")
(MaximumNumberOfIterations 1500)
(MaximumNumberOfSamplingAttempts 15)
(MaximumStepLength 1)
(Metric "AdvancedMattesMutualInformation")
(MovingImageDimension 3)
(MovingImagePyramid "MovingRecursiveImagePyramid")
(MovingInternalImagePixelType "float")
(NewSamplesEveryIteration "true")
(NumberOfHistogramBins 32)
(NumberOfResolutions 3)
(NumberOfSamplesForExactGradient 2500)
(NumberOfSpatialSamples 5000)
(Optimizer "AdaptiveStochasticGradientDescent")
(Registration "MultiResolutionRegistration")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")
(ResultImageFormat "nii.gz")
(ResultImagePixelType "float")
(Transform "EulerTransform")
(UseDirectionCosines "true")
(WriteIterationInfo "false")
(WriteResultImage "false")
