// *********************
// * ImageTypes
// *********************
(FixedInternalImagePixelType "float")
(FixedImageDimension 3)
(MovingInternalImagePixelType "float")
(MovingImageDimension 3)

// *********************
// * Components
// *********************
(Registration "MultiMetricMultiResolutionRegistration" )
(FixedImagePyramid "FixedSmoothingImagePyramid")
(MovingImagePyramid "MovingSmoothingImagePyramid")
(Interpolator "ReducedDimensionBSplineInterpolator")
(BSplineInterpolationOrder 1)
(Metric "DisplacementMagnitudePenalty")
(Optimizer "AdaptiveStochasticGradientDescent")
(ResampleInterpolator "FinalLinearInterpolator")
(Resampler "DefaultResampler")
(Transform "BSplineTransform")

(UseCyclicTransform "false")
(BSplineTransformSplineOrder 3)

// Parameters for varianceoverLastDimension metric
(MovingImageDerivativeScales 1.0 1.0 0.0)

// *********************
// * Optimizer settings
// *********************
(NumberOfResolutions 2)
(FinalGridSpacingInPhysicalUnits 3.0 3.0 4.0)
(GridSpacingSchedule 2.0 2.0 1.0 1.0 1.0 1.0)
(SP_A 20.0)
(SigmoidInitialTime 1.0)
(MaximumNumberOfIterations 2000)
(AutomaticParameterEstimation "true")

// *********************
// * Transform settings
// *********************
(HowToCombineTransforms "Compose" )

// *********************
// * Pyramid settings
// *********************
(ImagePyramidSchedule 0 0 0 0 0 0)

// *********************
// * Sampler parameters
// *********************
(ImageSampler "Random")
(NumberOfSpatialSamples 1000)
(CheckNumberOfSamples "true")
(MaximumNumberOfSamplingAttempts 10)
(NewSamplesEveryIteration "true")
(FinalBSplineInterpolationOrder 1)

// *********************
// * Output settings
// *********************
(WriteTransformParametersEachIteration "false" )
(WriteResultImage "true" )
(CompressResultImage "true" )
(WriteResultImageAfterEachResolution "false" )
(ShowExactMetricValue "false" )
(DefaultPixelValue 0)

