(AutomaticParameterEstimation "true")
(AutomaticScalesEstimation "true")
(AutomaticTransformInitialization "false")
(CheckNumberOfSamples "false")
(DefaultPixelValue 0)
(ErodeMask "true")
(FinalBSplineInterpolationOrder 3)
(FixedImageDimension 3)
(FixedImagePyramid "FixedSmoothingImagePyramid")
(FixedInternalImagePixelType "float")
(HowToCombineTransforms "Add")
(ImagePyramidSchedule 2 2 1 1 1 1 1 1 1)
(ImageSampler "RandomSparseMask")
(Interpolator "LinearInterpolator")
(MaximumNumberOfIterations 256 512 1024)
(MaximumNumberOfSamplingAttempts 8)
(Metric "AdvancedMattesMutualInformation" "AdvancedNormalizedCorrelation")
(Metric0Weight 0.5)
(Metric1Weight 0.5)
(MovingImageDimension 3)
(MovingImagePyramid "MovingSmoothingImagePyramid")
(MovingInternalImagePixelType "float")
(NewSamplesEveryIteration "true")
(NoiseCompensation "false")
(NumberOfHistogramBins 32 64 64)
(NumberOfResolutions 3)
(NumberOfSamplesForExactGradient 4096)
(NumberOfSpatialSamples 1024)
(Optimizer "AdaptiveStochasticGradientDescent")
(Registration "MultiMetricMultiResolutionRegistration")
(ResampleInterpolator "FinalNearestNeighborInterpolator" "FinalNearestNeighborInterpolator")
(Resampler "DefaultResampler")
(ResultImageFormat "nii")
(ShowExactMetricValue "false")
(Transform "EulerTransform")
(WriteIterationInfo "true")
(WriteResultImage "false")
